### ISSUE TITLE
Rstudio hardening - ProB additional features

### ISSUE THREAD

**Issue by wg102** [StatCan/kubeflow-containers#199]
This is related to the Rstudio hardening issue https://github.com/StatCan/daaas/issues/352

When in Protected B, we want to block the upload, download and possibly the package installation.
To do so, we need to know if we are in ProB, and if so add the following configuration to etc/rstudio/rsession.conf
```
    allow-file-downloads=0
    allow-file-uploads=0
```
and possibly `allow-package-installation=0`.

The platform should already block uploads and downloads, but this would be a better UX, since it will remove the button from Rstudio-server UI.
**Note**: Even if the button is removed from the UI, the functionality is still possible through r, which is why it is important to make sure this is covered at platform level

Suggestion:
Have the Rstudio image be aware of whether or not it's ProB 
Possible way: the startup script could ping some URL or IP, and if it can't get a network route then it can assume it's isolated and set the corresponding flags.

**Comment by wg102** [comment]
The authorization policy was created, but there is an issue with the paths. 
The path has to be exact, and Regex do not seem to be valid for authorization policies yet. 
(Refer github issue)

The rules to add would be:     
```
- operation:
        methods: ["POST"]
        paths: ["*/rstudio/upload"]
    - operation:
        methods: ["GET"]
        paths: ["/notebook/bob/rstudio/rstudio/export*"] # This one still needs work
```

But with any namespace and notebook name.
